#!/bin/sh /etc/rc.common
START=100
STOP=10

start() {
    while ! docker info > /dev/null 2>&1; do     
        sleep 5                      
    done                             
    cd /root/chirpstack-docker
    /usr/bin/docker-compose up -d 
}                                            
                                
stop() {                        
    cd /root/chirpstack-docker
    /usr/bin/docker-compose down
}