#!/bin/sh /etc/rc.common
START=99
STOP=10

start() {
    echo "$(date): Waiting for Docker to fully start..."
    cd /etc/lora/
    lora_pkt_fwd -c ./global_conf.json.sx1250
}

stop() {
    echo "$(date): Stopping lora_pkt_fwd"
    # Find the PID of lora_pkt_fwd and kill it
    PID=$(ps | grep "lora_pkt_fwd -c ./global_conf.json.sx1250" | grep -v grep | awk '{print $1}')
    if [ -n "$PID" ]; then
        kill $PID
    fi
} 